# Generated by Django 4.2.4 on 2023-08-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_review_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='edit_by_admin',
            field=models.CharField(default=1, max_length=50, verbose_name='Изменен админом'),
            preserve_default=False,
        ),
    ]
